---
- name: create lastpass .config dir
  become_user: "{{user}}"
  file:
    path: /home/{{user}}/.config/lpass
    state: directory

- name: create lastpass .local dir
  become_user: "{{user}}"
  file:
    path: /home/{{user}}/.local/share/lpass
    state: directory